#!/bin/bash
PLUGIN_DIR="$HOME/Library/Application Support/Colloquy/PlugIns"
install -d "$PLUGIN_DIR"
install cw.fscript "$PLUGIN_DIR"
install cw.rb "$PLUGIN_DIR"
echo "run '/fscript load cw' or \
'/fscript reload cw' in Colloquy to load the latest version"
