#!/bin/bash
PLUGIN_DIR="$HOME/Library/Application Support/Colloquy/PlugIns"
PLUGIN_CW="$PLUGIN_DIR"/cw
install -d "$PLUGIN_CW"
install cw.fscript "$PLUGIN_DIR"
install cw.rb "$PLUGIN_CW"
install `which ebook2cw` "$PLUGIN_CW"
echo "run '/fscript load cw' or \
'/fscript reload cw' in Colloquy to load the latest version"
